---
- name: Deploy Java Web Calculator
  hosts: all
  become: yes
  
  tasks:
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk
        state: present
        
    - name: Install Apache Tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
        dest: /usr/local
        
        
    - name: extract tomcat packages
      unarchive:
         src: /usr/local/apache-tomcat-10.0.27.tar.gz
         dest: /usr/local
         remote_src: yes   
        
    - name: Install git
      yum:
        name: git
        state: present

    - name: Clone Apache-tomcat repository
      git:
        repo: https://github.com/jessyewoma/Apache-tomcat.git
        dest: /home/ec2-user/Apache-tomcat
        
    - name: Copy web application to Tomcat
      copy:
        src: /home/ec2-user/Apache-tomcat/JavaWebCalculator/src/main/java
        dest: /home/ec2-user/apache-tomcat-10.0.27/webapps/
        mode: 0755
    
    - name: deploying the war file to target servers
      copy:
        src: /var/lib/jenkins/workspace/Apache-tomcat/
        dest: /usr/local/apache-tomcat-10.0.27/webapps
        mode: 0755
    
    
    - name: start tomcat services
      shell: nohup /usr/local/apache-tomcat-10.0.27/bin/startup.sh

      
    - name: Wait for Apache Tomcat to start
      wait_for:
        port: 8080
        state: started
